-- Question 01: Global Sales Heatmap (Demographic Aggregation) Requirement: The Head of Marketing wants to analyze revenue distribution across different countries. Write a query that extracts each unique country name, the total number of orders placed from that country, and the total accumulated sales revenue (calculated as quantity multiplied by unit price). The final output must be sorted in descending order to place the highest-revenue-generating country at the very top.
-- Solution:
SELECT
    u.country,
    COUNT(o.order_id) AS total_orders,
    SUM(oi.quantity * oi.unit_price) AS total_sales
FROM
    users u
    JOIN orders o ON u.user_id = o.user_id
    JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY
    u.country
ORDER BY
    total_sales DESC;

-- Question 02: The Underperforming Manager Audit (Self-Join + Aggregation) Requirement: The Operations team is conducting an internal organizational audit. They require a report showing each Manager's full name (first name combined with last name), their assigned department, and the total count of direct reports working under them. Restrict the output exclusively to managers who oversee an active team of more than 2 employees, using a HAVING clause, and sort by the largest team size.
-- Solution:
SELECT
    m.first_name || ' ' || m.last_name AS manager_full_name,
    m.department,
    COUNT(e.employee_id) AS total_employees
FROM
    employees m
    JOIN employees e ON e.manager_id = m.employee_id
GROUP BY
    m.employee_id, m.first_name, m.last_name, m.department
HAVING
    COUNT(e.employee_id) > 2
ORDER BY
    total_employees DESC;

-- Question 03: Category Price-Gap & Inventory Value Analytics Requirement: The Retail Director needs a deep-dive financial analysis across all product categories (e.g., Electronics, Apparel). For each individual category, calculate three specific operational metrics: the highest retail price currently listed (MAX), the lowest supplier cost price recorded (MIN), and the total estimated dollar valuation of the existing stock (calculated as stock quantity multiplied by retail price).
-- Solution:
SELECT
    category,
    MAX(retail_price) AS max_retail_price,
    MIN(cost_price) AS min_cost_price,
    SUM(stock_quantity * retail_price) AS total_stock_valuation
FROM
    products
GROUP BY
    category;

-- Question 04: Order Leakage & Status Breakdown (Multi-Table Stats) Requirement: The Supply Chain Manager wants to evaluate operational bottlenecks and see how much capital is tied up across various order lifecycle stages (Delivered, Pending, Cancelled). Generate a breakdown displaying each order status, the total count of orders within that status, and the absolute gross revenue generated by the items contained within those orders.
-- Solution:
SELECT
    o.order_status,
    COUNT(o.order_id) AS total_orders,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM
    orders o
    JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY
    o.order_status;

-- Question 05: High-Value Inventory Leakage (Dead Stock Valuation) Requirement: The Head of Warehouse Logistics requires a report on high-value "dead stock"—products that are occupying warehouse space but have never been purchased. Perform a LEFT JOIN between the products and order items tables to extract the product name, product category, and current warehouse stock quantity for items that have no corresponding order records (IS NULL) and carry a retail price strictly above $50.
-- Solution:
SELECT
    p.product_name,
    p.category,
    p.stock_quantity
FROM
    products p
    LEFT JOIN order_items oi ON p.product_id = oi.product_id
WHERE
    oi.product_id IS NULL
    AND p.retail_price > 50;

-- Question 06: Cross-Department Salary Gap Analysis (Double Join) Requirement: The HR Director is auditing organizational reporting lines and cross-departmental salary distributions. Generate a comprehensive roster showing each employee's full name, their department, and their current salary. To verify whether any manager is cross-handling a team outside their own domain, display the corresponding manager's full name and the manager's assigned department side by side.
-- Solution:
SELECT
    e.first_name || ' ' || e.last_name AS employee_full_name,
    e.department AS employee_department,
    e.salary AS employee_salary,
    m.first_name || ' ' || m.last_name AS manager_full_name,
    m.department AS manager_department
FROM
    employees e
    LEFT JOIN employees m ON e.manager_id = m.employee_id;

-- Question 07: Customer Lifetime Value (CLV) with Order Count Restrictions Requirement: The CEO wants to evaluate long-term brand loyalty and identify premium repeat customers. Write a query to extract the username, the total count of orders placed, and the total life-to-date customer spending (quantity multiplied by unit price). Filter the results to isolate users who have placed a minimum of 4 distinct orders, excluding any orders that were 'Cancelled', and rank them with the highest spenders at the top.
-- Solution:
SELECT
    u.username,
    COUNT(o.order_id) AS total_order_count,
    SUM(oi.quantity * oi.unit_price) AS total_spending
FROM
    users u
    LEFT JOIN orders o ON u.user_id = o.user_id
    LEFT JOIN order_items oi ON o.order_id = oi.order_id
WHERE
    o.order_status != 'Cancelled'
GROUP BY
    u.username
HAVING
    COUNT(o.order_id) >= 4
ORDER BY
    total_spending DESC;

-- Question 08: Underperforming Products with Active Orders (The Slow Movers) Requirement: The Inventory Management team suspects that certain products are underperforming significantly despite appearing in active customer orders. Extract the product name, category, and the absolute sum of all units sold. The output must strictly isolate active products whose total aggregated units sold across all orders is strictly less than 5 items.
-- Solution:
SELECT
    p.product_name,
    p.category,
    SUM(oi.quantity) AS total_quantity_sold
FROM
    products p
    INNER JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY
    p.product_name,
    p.category
HAVING
    SUM(oi.quantity) < 5;

-- Question 09: High-Value Order Basket Audit (The Whale Orders) Requirement: The Finance team wants to audit single, high-value "whale" transactions that significantly impact cash flow. Write a query to retrieve the unique order ID, the username of the customer who placed the order, and the gross financial invoice value of that single basket (calculated as the sum of quantity multiplied by unit price). Restrict the report to individual orders where the total invoice value crosses a threshold of $250, ordered from highest value down.
-- Solution:
SELECT
    o.order_id,
    u.username,
    SUM(oi.quantity * oi.unit_price) AS total_order_value
FROM
    orders o
    INNER JOIN users u ON o.user_id = u.user_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY
    o.order_id,
    u.username
HAVING
    SUM(oi.quantity * oi.unit_price) > 250
ORDER BY
    total_order_value DESC;

-- Question 10: Complete Employee-Sales Mapping (LEFT JOIN on Sales) Requirement: For an upcoming sales performance review meeting, HR needs to identify passive or non-performing sales representatives who have not processed a single transaction. Apply a LEFT JOIN between the employees and orders tables to pull the full name and department of all internal employees who have zero mapping entries in the orders table (where the order's associated employee ID IS NULL).
-- Solution:
SELECT
    e.first_name || ' ' || e.last_name AS employee_full_name,
    e.department
FROM
    employees e
    LEFT JOIN orders o ON e.employee_id = o.employee_id
WHERE
    o.employee_id IS NULL;