-- Advanced Analysis Queries --
-- Running total revenue by hotel over time. For each hotel, calculate a running (cumulative) total of adr * (stays_in_weekend_nights + stays_in_week_nights) ordered by arrival_date, for non-cancelled bookings only. Hint: window function — SUM(...) OVER (PARTITION BY hotel_id ORDER BY arrival_date).
-- Solution:
-- Rank bookings by ADR within each market segment. For every booking, show its rank (1 = highest adr) within its own market_segment — without collapsing rows like GROUP BY would. Hint: RANK() or DENSE_RANK() OVER (PARTITION BY market_segment ORDER BY adr DESC).
-- Soolution:
-- Month-over-month change in booking volume. For each hotel, show total bookings per month and the change from the previous month. Hint: build a monthly count first (CTE), then use LAG() to pull the prior month's value into the same row.
-- Solution:
-- Top 3 highest-ADR bookings per country. Find the 3 bookings with the highest adr for each country — a classic "top-N per group" problem. Hint: ROW_NUMBER() OVER (PARTITION BY country ORDER BY adr DESC) inside a CTE, then filter WHERE row_num <= 3 in the outer query — a plain WHERE can't filter on a window function directly.
-- Solution:
-- Identify guests who are "at risk" using a moving pattern. For each market_segment, calculate the 3-booking moving average of adr ordered by arrival_date, to see if pricing is trending up or down within a segment. Hint: AVG(adr) OVER (PARTITION BY market_segment ORDER BY arrival_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW).
-- Solution:
-- Percentage of total revenue each market segment contributes. For each market_segment, show its total revenue and what percentage that is of the grand total — in the same query, no separate lookup. Hint: SUM(...) OVER () with no PARTITION BY gives you the grand total alongside the grouped rows.
-- Solution:
-- Find the gap between a hotel's best and worst month. Using a CTE that aggregates bookings by hotel and month, find the difference between each hotel's highest-volume month and lowest-volume month. Hint: build the monthly summary as a CTE, then aggregate again on top of it with MAX() - MIN().
-- Solution:
-- Classify each booking as above/below its hotel's average ADR. For every individual booking, add a column showing whether its adr is above or below the average adr for that specific hotel — one row per booking, not grouped. Hint: correlated subquery (which you've already practiced) OR AVG(adr) OVER (PARTITION BY hotel_id) — try both and compare readability/performance.
-- Solution:
-- Find consecutive months where cancellation rate increased. Using monthly cancellation rate as a CTE, find every month where the cancellation rate was higher than the previous month's. Hint: same LAG() pattern as question 3, but comparing a calculated rate instead of a raw count.
-- Solution:
-- Segment customers into ADR quartiles. Split all bookings into 4 equal-sized groups (quartiles) based on adr, and show the average total_of_special_requests per quartile — do higher-paying bookings request more? Hint: NTILE(4) OVER (ORDER BY adr) assigns each row a quartile number 1-4; then GROUP BY on that quartile number.
-- Solution: